# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: test on pr

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    #    ios 빌드시 macOs로 변경 필요

    steps:
      - name: check out branch
        uses: actions/checkout@v4
      - name: set up sdk
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.4
      - run: flutter --version
      - name: flutter clean
        run: flutter clean
      - name: remove pubspec.lock
        run: export LANG=en_US.UTF-8 && rm -f pubspec.lock
      - name: get packages
        run: flutter pub get
      - name: run test
        run: flutter test
      - name: build android
        run: flutter build appbundle
          #      - name: build ios
          #        run: flutter build

